on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image and push to Docker Hub
        uses: docker/build-push-action@v6.6.0
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: dennisgerike/flickr-photos-to-postcard-converter:${{ github.ref_name }},dennisgerike/flickr-photos-to-postcard-converter:latest

  bump-version:
    needs: [
      build-docker-image,
    ]
    uses: ./.github/workflows/bump-version.yaml
