on:
  workflow_call:

jobs:
  bump-version:
    name: "Update package version to match release version"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Bump version
        run: npm version ${{ github.ref_name }} -m "Updating package version to %s"
      - name: Push new version
        uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: "Bump version"
