name: Build And Publish Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  functionality-tests:
    uses: ./.github/workflows/run-functionality-tests.yaml

  behavior-tests:
    uses: ./.github/workflows/run-behavior-tests.yaml
    secrets: inherit

  build-docker-image:
    needs: [
      functionality-tests,
      behavior-tests,
    ]
    uses: ./.github/workflows/build-docker-image.yaml
    secrets: inherit
