on:
  workflow_call:

jobs:
  create-test-coverage-report:
    name: "Create Test Coverage Report"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node.js dependencies
        run: npm ci
      - name: Download raw coverage report
        uses: actions/download-artifact@v4.1.7
        with:
          name: test-coverage
      - name: Create 'Coveralls' coverage report
        uses: coverallsapp/github-action@v2.3.0
        with:
          file: lcov.info
          format: lcov

