on:
  workflow_call:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  create-test-report:
    name: "Create Test Report"
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1.9.1
        with:
          artifact: test-results
          name: "Test Results (Functionality Tests)"
          path: 'junit.xml'
          reporter: jest-junit
