on:
  workflow_call:

jobs:
  create-test-coverage-report:
    name: "Create Test Coverage Report"
    runs-on: ubuntu-latest
    steps:
      - name: Download raw coverage report
        uses: actions/download-artifact@v4.1.7
        with:
          name: test-coverage
      - run: ls -la
      - name: Create HTML coverage report
        uses: coverallsapp/github-action@v2.3.0
        with:
          file: lcov.info
          format: lcov

