on:
  workflow_call:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  run-functionality-tests:
    name: "Run Functionality Tests (Jest)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run Jest tests
        run: npm run test-functionality-with-coverage
      - name: Archive test report
        uses: actions/upload-artifact@v4.3.3
        if: success() || failure()
        with:
          name: test-results
          path: test-reports/junit.xml

  generate-test-report:
    needs: [
      run-functionality-tests,
    ]
    uses: ./.github/workflows/create-test-report-junit.yaml
