name: Run All Test Suites

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  functionality-tests:
    uses: ./.github/workflows/run-functionality-tests.yaml

  behavior-tests:
    uses: ./.github/workflows/run-behavior-tests.yaml
