on:
  workflow_call:

jobs:
  run-functionality-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run Jest tests
        run: npm run test-functionality
      - name: Test report
        uses: dorny/test-reporter@v1.9.1
        if: success() || failure()
        with:
          artifact: test-results
          name: Functionality Tests
          path: 'test-reports/junit.xml'
          reporter: jest-junit
