on:
  workflow_call:
    secrets:
      FLICKR_API_KEY:
        required: true
      CUCUMBER_PUBLISH_TOKEN:
        required: true

jobs:
  run-behavior-tests:
    name: "Run Behavior Tests (Gherkin/Cucumber)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run Cucumber tests
        env:
          FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}
          CUCUMBER_PUBLISH_TOKEN: ${{ secrets.CUCUMBER_PUBLISH_TOKEN }}
        run: npm run test-behavior-and-publish
      - name: Archive test reports
        uses: actions/upload-artifact@v4.3.3
        if: success() || failure()
        with:
          name: test-results-cucumber
          path: test-reports/cucumber-report.*

  upload-test-results:
    needs: [
      run-behavior-tests,
    ]
    uses: ./.github/workflows/upload-test-results-to-xray.yaml
    secrets: inherit
